export interface Character {
  id: string;
  name: string;
  role: string; // e.g. "Protagonista", "Antagonista", "Aliado", "Informante"
  visualTraits: string; // Immutable facial & physical traits for AI consistency
  clothing: string;
  personality: string;
  voiceStyle?: string;
  voicePrompt: string; // Detailed voice prompt (timbre, tone, cadence, accent) to maintain consistent vocal audio
  avatarUrl?: string;
  referenceImages?: string[];
  stepIntroduced?: number; // Step number when introduced by LLM
}

export interface Prop {
  id: string;
  name: string;
  description: string;
  visualAppearance: string; // Immutable visual appearance for AI consistency
  narrativeSignificance: string;
  imageUrl?: string; // Reference image sent to video models
  stepIntroduced?: number; // Step number when introduced
  ownerCharacterId?: string; // ID of the character who owns/introduces this prop
  ownerCharacterName?: string;
  icon?: string;
}

export interface SceneEnvironment {
  id: string;
  name: string;
  lighting: string;
  atmosphere: string;
  colorPalette: string;
  architecturalStyle: string;
}

export interface DecisionOption {
  id: 'A' | 'B';
  title: string;
  text: string;
  dramaticHook: string;
  expectedConsequence: string;
  votes: number;
}

export interface SubtitleCue {
  id?: string;
  start: number; // in seconds (0 to 15)
  end: number;   // in seconds (0 to 15)
  speaker?: string; // e.g. "Kael", "Lyra"
  text: string; // English dialogue / narration
  textEs?: string; // Optional Spanish translation for multilingual subtitles
}

export interface MovieStep {
  stepNumber: number; // 1 to 100
  title: string;
  synopsis: string;
  dialogueSnippet?: string;
  subtitles?: SubtitleCue[]; // Timed subtitles for the 15-second clip
  voiceDirection?: string; // Character voice prompt and emotional direction for consistent audio
  visualPrompt: string; // Detailed Image prompt with character & prop consistency anchors
  cameraMotionPrompt: string; // Camera movement & cinematography prompt
  videoUrl: string; // 15-second video clip URL
  thumbnailUrl?: string;
  duration: number; // exactly 15 seconds
  votingWindowSeconds: number; // exactly 10 seconds
  options: [DecisionOption, DecisionOption];
  selectedOption?: 'A' | 'B';
  wasRandomPick?: boolean;
  activeCharacters: string[];
  activeProps: string[];
  newCharacter?: Character; // New character introduced in this step by the LLM
  newProp?: Prop; // Associated signature prop created specifically with this new character
  referenceVideoUrl?: string; // Previous video URL passed as continuity reference
  propReferenceImages?: string[]; // Prop image URLs passed as references to fal.ai
  environment: string;
  createdAt: string;
}

export interface MovieBible {
  characters: Character[];
  props: Prop[];
  environments: SceneEnvironment[];
  cinematicStyle: string; // e.g. "Anamorphic 35mm Panavision, Dark Cyberpunk, Moody Teals and Neon Amber"
  targetTheme: string;
}

export interface Movie {
  id: string;
  title: string;
  genre: string;
  tagline: string;
  initialPlot: string; // Generated master story & arc by the LLM
  masterArcThread: string;
  status: 'streaming' | 'completed' | 'paused';
  currentStep: number;
  totalSteps: number; // 100 steps total
  bible: MovieBible;
  steps: MovieStep[];
  createdAt: string;
  completedAt?: string;
  totalVotesCast: number;
  finalSummary?: string; // Full narrative retrospective generated by LLM when movie finishes 100 steps
  finalSynopsis?: string; // New definitive synopsis created by LLM upon movie completion
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  text: string;
  timestamp: string;
  createdAtMs?: number;
  isSystem?: boolean;
  votedOption?: 'A' | 'B';
  votesCount?: number;
  hasUserVoted?: boolean;
}

export type PlaybackPhase = 'PLAYING' | 'VOTING' | 'GENERATING' | 'COMMERCIAL_BREAK';

export type ImmersiveAdType = 'commercial_break' | 'in_scene_overlay';

export interface ImmersiveAd {
  id: string;
  brandName: string;
  title: string;
  tagline?: string;
  description?: string;
  type: ImmersiveAdType;
  videoUrl?: string;
  imageUrl?: string;
  ctaText: string;
  ctaUrl?: string;
  perkReward?: string; // e.g. "+50 Audience Community Votes"
  duration: number; // in seconds, default 10s
  isActive: boolean;
  frequencySteps?: number; // e.g. every 5 steps
  stepTrigger?: number; // specific step number or null
  impressions: number;
  clicks: number;
  createdAt?: string;
  /**
   * Screenplay/direction script passed to fal.ai when generating the immersive ad clip.
   * The model is instructed to continue the film world seamlessly while weaving in the brand.
   * If absent the orchestrator falls back to a generic continuation prompt with the brand name.
   */
  cinematicPrompt?: string;
  /**
   * URL of the fal.ai-generated ad clip. Populated at runtime when the commercial break is triggered.
   * Stored in Supabase so the ad can be replayed consistently across sessions.
   */
  generatedAdVideoUrl?: string;
  /**
   * Flag indicating this ad is playing a previously generated archive version.
   */
  isArchiveReplay?: boolean;
}

export interface AdsConfig {
  autoAdsEnabled: boolean;
  adIntervalSteps: number; // Interval of movie steps between ads (e.g. every 5 steps)
  lastAdStep: number;
}

export interface CinemaState {
  movie: Movie;
  phase: PlaybackPhase;
  timeRemaining: number; // in seconds
  phaseDuration?: number; // Initial duration in seconds of current phase
  phaseStartedAt?: string | number; // Epoch ms or ISO string when current phase started
  phaseEndsAt?: string | number; // Epoch ms or ISO string when current phase will end
  totalAudience: number;
  votesA: number;
  votesB: number;
  hasUserVoted?: 'A' | 'B' | null;
  activeStep: MovieStep;
  isLive: boolean;
  isPaused?: boolean;
  isGenerationPaused?: boolean;
  activeAd?: ImmersiveAd | null;
  adsConfig?: AdsConfig;
  apiStatus: {
    hasDeepseek: boolean;
    hasFal: boolean;
    isMockMode: boolean;
  };
}

