export interface Character {
  id: string;
  name: string;
  role: string; // e.g. "Protagonista", "Antagonista", "Aliado", "Informante"
  visualTraits: string; // Immutable facial & physical traits for AI consistency
  clothing: string;
  personality: string;
  voiceStyle?: string;
  voicePrompt: string; // Detailed voice prompt (timbre, tone, cadence, accent) to maintain consistent vocal audio
  avatarUrl?: string;
  referenceImages?: string[];
  stepIntroduced?: number; // Step number when introduced by LLM
}

export interface Prop {
  id: string;
  name: string;
  description: string;
  visualAppearance: string; // Immutable visual appearance for AI consistency
  narrativeSignificance: string;
  imageUrl?: string; // Reference image sent to video models
  stepIntroduced?: number; // Step number when introduced
  ownerCharacterId?: string; // ID of the character who owns/introduces this prop
  ownerCharacterName?: string;
  icon?: string;
}

export interface SceneEnvironment {
  id: string;
  name: string;
  lighting: string;
  atmosphere: string;
  colorPalette: string;
  architecturalStyle: string;
}

export interface DecisionOption {
  id: 'A' | 'B';
  title: string;
  text: string;
  dramaticHook: string;
  expectedConsequence: string;
  votes: number;
  visualPrompt?: string; // Pre-generated Cinematique 6-layer visual prompt for Shot 1 (Opening)
  cameraMotionPrompt?: string; // Pre-generated Cinematique 4-layer camera motion prompt for Shot 1
  visualPrompt2?: string; // Pre-generated Cinematique visual prompt for Shot 2 (Climax / Resolution)
  cameraMotionPrompt2?: string; // Pre-generated Cinematique camera motion prompt for Shot 2
  synopsis?: string; // Pre-generated synopsis if this option wins
  dialogueSnippet?: string; // Pre-generated spoken dialogue if this option wins
  subtitles?: SubtitleCue[]; // Pre-generated timed subtitles if this option wins
  voiceDirection?: string; // Character voice and emotional cadence
}

export interface SubtitleCue {
  id?: string;
  start: number; // in seconds (0 to 30)
  end: number;   // in seconds (0 to 30)
  speaker?: string; // e.g. "Kael", "Lyra"
  text: string; // English dialogue / narration
  textEs?: string; // Optional Spanish translation for multilingual subtitles
}

export interface MovieStep {
  stepNumber: number; // 1 to TOTAL_STEPS (50)
  title: string;
  synopsis: string;
  dialogueSnippet?: string;
  subtitles?: SubtitleCue[]; // Timed subtitles for the scene clip
  voiceDirection?: string; // Character voice prompt and emotional direction for consistent audio
  visualPrompt: string; // Detailed prompt for Shot 1 (Apertura)
  cameraMotionPrompt: string; // Camera movement prompt for Shot 1
  videoUrl: string; // Shot 1 video clip URL (15s)
  visualPrompt2?: string; // Detailed prompt for Shot 2 (Clímax / Desenlace)
  cameraMotionPrompt2?: string; // Camera movement prompt for Shot 2
  videoUrl2?: string; // Shot 2 video clip URL (15s)
  thumbnailUrl?: string;
  hasMidRollAd?: boolean; // True if this scene includes an immersive sponsor ad in Block 2
  adVideoUrl?: string; // In-world sponsor ad video clip URL (15s in Block 2)
  duration: number; // 30 seconds (or 45s when hasMidRollAd is true)
  votingWindowSeconds: number; // exactly 10 seconds
  options: [DecisionOption, DecisionOption];
  selectedOption?: 'A' | 'B';
  wasRandomPick?: boolean;
  activeCharacters: string[];
  activeProps: string[];
  newCharacter?: Character; // New character introduced in this step by the LLM
  newProp?: Prop; // Associated signature prop created specifically with this new character
  referenceVideoUrl?: string; // Previous video URL passed as continuity reference
  propReferenceImages?: string[]; // Prop image URLs passed as references to fal.ai
  environment: string;
  createdAt: string;
}

export interface MovieBible {
  characters: Character[];
  props: Prop[];
  environments: SceneEnvironment[];
  cinematicStyle: string; // e.g. "Anamorphic 35mm Panavision, Dark Cyberpunk, Moody Teals and Neon Amber"
  targetTheme: string;
}

export interface Movie {
  id: string;
  title: string;
  genre: string;
  tagline: string;
  initialPlot: string; // Generated master story & arc by the LLM
  masterArcThread: string;
  status: 'streaming' | 'completed' | 'paused';
  currentStep: number;
  totalSteps: number; // 50 steps total
  bible: MovieBible;
  steps: MovieStep[];
  createdAt: string;
  completedAt?: string;
  totalVotesCast: number;
  finalSummary?: string; // Full narrative retrospective generated by LLM when movie finishes 50 steps
  finalSynopsis?: string; // New definitive synopsis created by LLM upon movie completion
}

export interface ChatMessage {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  text: string;
  timestamp: string;
  createdAtMs?: number;
  isSystem?: boolean;
  votedOption?: 'A' | 'B';
  usedForInfluence?: boolean;
  votesCount?: number;
  hasUserVoted?: boolean;
}

export type PlaybackPhase = 'PLAYING' | 'VOTING' | 'OPTION_VOTING' | 'GENERATING' | 'COMMERCIAL_BREAK' | 'BLOCKBUSTER_VOTING' | 'MOVIE_VOTING';

export const isOptionVotingPhase = (phase?: PlaybackPhase | string | null): boolean =>
  phase === 'VOTING' || phase === 'OPTION_VOTING';

export const isMovieVotingPhase = (phase?: PlaybackPhase | string | null): boolean =>
  phase === 'BLOCKBUSTER_VOTING' || phase === 'MOVIE_VOTING';

// Total scenes per film: 50 x 15s. Narrative arc:
//   1-10 establishment + central problem, 11-39 development, 40-49 denouement, 50 = THE END
export const TOTAL_STEPS = 50;

export interface BlockbusterCandidate {
  id: 'A' | 'B' | 'C' | 'D';
  title: string;
  logline: string;
  genre: string;
  premise: string;
}

export type ImmersiveAdType = 'commercial_break' | 'in_scene_overlay';

export interface ImmersiveAd {
  id: string;
  brandName: string;
  title: string;
  tagline?: string;
  description?: string;
  type: ImmersiveAdType;
  videoUrl?: string;
  imageUrl?: string;
  ctaText: string;
  ctaUrl?: string;
  perkReward?: string; // e.g. "+50 Audience Community Votes"
  duration: number; // in seconds, default 10s
  isActive: boolean;
  frequencySteps?: number; // e.g. every 5 steps
  stepTrigger?: number; // specific step number or null
  impressions: number;
  clicks: number;
  createdAt?: string;
  /**
   * Screenplay/direction script passed to fal.ai when generating the immersive ad clip.
   * The model is instructed to continue the film world seamlessly while weaving in the brand.
   * If absent the orchestrator falls back to a generic continuation prompt with the brand name.
   */
  cinematicPrompt?: string;
  /**
   * URL of the fal.ai-generated ad clip. Populated at runtime when the commercial break is triggered.
   * Stored in Supabase so the ad can be replayed consistently across sessions.
   */
  generatedAdVideoUrl?: string;
  /**
   * Flag indicating this ad is playing a previously generated archive version.
   */
  isArchiveReplay?: boolean;
}

export interface AdsConfig {
  autoAdsEnabled: boolean;
  adIntervalSteps: number; // Interval of movie steps between ads (e.g. every 5 steps)
  lastAdStep: number;
}

export interface CinemaState {
  movie: Movie;
  phase: PlaybackPhase;
  timeRemaining: number; // in seconds
  phaseDuration?: number; // Initial duration in seconds of current phase
  phaseStartedAt?: string | number; // Epoch ms or ISO string when current phase started
  phaseEndsAt?: string | number; // Epoch ms or ISO string when current phase will end
  totalAudience: number;
  votesA: number;
  votesB: number;
  hasUserVoted?: 'A' | 'B' | null;
  blockbusterUserVoted?: 'A' | 'B' | 'C' | 'D' | null;
  activeStep: MovieStep;
  isLive: boolean;
  isPaused?: boolean;
  isGenerationPaused?: boolean;
  videoModel?: string;
  videoResolution?: string | null;
  blockbusterCandidates?: BlockbusterCandidate[];
  blockbusterVoteCounts?: Record<'A' | 'B' | 'C' | 'D', number>;
  blockbusterWinner?: { id?: 'A' | 'B' | 'C' | 'D'; title: string; logline?: string; genre?: string; premise?: string } | null;
  activeAd?: ImmersiveAd | null;
  adsConfig?: AdsConfig;
  apiStatus?: {
    hasDeepseek: boolean;
    hasFal: boolean;
    isMockMode: boolean;
  };
}

export interface ContactMessage {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  status: 'unread' | 'read' | 'archived';
  created_at: string;
}

